"""Canonical error taxonomy for Construction Runtime v0.2.

All runtime errors must use constants from this module.
No inline error strings in validators, engines, or generators.
"""


# ── Parse Errors ──────────────────────────────────────────
PARSE_EMPTY_INPUT = "PARSE_EMPTY_INPUT"
PARSE_NORMALIZATION_FAILED = "PARSE_NORMALIZATION_FAILED"
PARSE_DIMENSION_MISSING = "PARSE_DIMENSION_MISSING"
PARSE_COMPONENT_UNNAMED = "PARSE_COMPONENT_UNNAMED"
PARSE_SECTION_MALFORMED = "PARSE_SECTION_MALFORMED"
PARSE_CONSTRAINT_EMPTY = "PARSE_CONSTRAINT_EMPTY"

# ── Normalize Errors ─────────────────────────────────────
NORMALIZE_INVALID_ENCODING = "NORMALIZE_INVALID_ENCODING"
NORMALIZE_CONTROL_CHARS = "NORMALIZE_CONTROL_CHARS"

# ── Model Errors ──────────────────────────────────────────
MODEL_MISSING_FIELD = "MODEL_MISSING_FIELD"
MODEL_INVALID_TYPE = "MODEL_INVALID_TYPE"
MODEL_ENUM_VIOLATION = "MODEL_ENUM_VIOLATION"

# ── Domain Errors ─────────────────────────────────────────
DOMAIN_INVALID_ASSEMBLY = "DOMAIN_INVALID_ASSEMBLY"
DOMAIN_INCOMPATIBLE_MATERIAL = "DOMAIN_INCOMPATIBLE_MATERIAL"
DOMAIN_UNSUPPORTED_SUBSTRATE = "DOMAIN_UNSUPPORTED_SUBSTRATE"
DOMAIN_MISSING_PERFORMANCE_CONSTRAINT = "DOMAIN_MISSING_PERFORMANCE_CONSTRAINT"
DOMAIN_INVALID_ASSEMBLY_COMBINATION = "DOMAIN_INVALID_ASSEMBLY_COMBINATION"

# ── Geometry Errors ───────────────────────────────────────
GEOMETRY_INSUFFICIENT_DIMENSIONS = "GEOMETRY_INSUFFICIENT_DIMENSIONS"
GEOMETRY_PANEL_LAYOUT_FAILED = "GEOMETRY_PANEL_LAYOUT_FAILED"
GEOMETRY_OVERLAP_DETECTED = "GEOMETRY_OVERLAP_DETECTED"
GEOMETRY_NEGATIVE_DIMENSION = "GEOMETRY_NEGATIVE_DIMENSION"
GEOMETRY_MISSING_UNIT = "GEOMETRY_MISSING_UNIT"

# ── Validation Errors ─────────────────────────────────────
VALIDATION_STRUCTURAL_FAILED = "VALIDATION_STRUCTURAL_FAILED"
VALIDATION_DOMAIN_FAILED = "VALIDATION_DOMAIN_FAILED"
VALIDATION_GENERATION_FAILED = "VALIDATION_GENERATION_FAILED"
VALIDATION_UNKNOWN_INPUT_TYPE = "VALIDATION_UNKNOWN_INPUT_TYPE"
VALIDATION_EMPTY_DATA = "VALIDATION_EMPTY_DATA"

# ── Generation Errors ─────────────────────────────────────
GENERATION_LAYER_MAPPING_MISSING = "GENERATION_LAYER_MAPPING_MISSING"
GENERATION_GEOMETRY_INCOMPLETE = "GENERATION_GEOMETRY_INCOMPLETE"
GENERATION_ANNOTATION_INCOMPLETE = "GENERATION_ANNOTATION_INCOMPLETE"
GENERATION_SVG_UNSUPPORTED_ENTITY = "GENERATION_SVG_UNSUPPORTED_ENTITY"
GENERATION_INSTRUCTION_INVALID = "GENERATION_INSTRUCTION_INVALID"

# ── Deliverable Errors ────────────────────────────────────
DELIVERABLE_DXF_EXPORT_FAILED = "DELIVERABLE_DXF_EXPORT_FAILED"
DELIVERABLE_SVG_EXPORT_FAILED = "DELIVERABLE_SVG_EXPORT_FAILED"
DELIVERABLE_MISSING_FORMAT = "DELIVERABLE_MISSING_FORMAT"

# ── Pipeline Errors ───────────────────────────────────────
PIPELINE_STAGE_FAILED = "PIPELINE_STAGE_FAILED"
PIPELINE_CONTRACT_VIOLATION = "PIPELINE_CONTRACT_VIOLATION"
PIPELINE_ABORT = "PIPELINE_ABORT"
